---
- name: This Playbook is to create multiple users
  hosts: all
  become: true
  tasks:
  - name: creating users
    user:
      name: "{{item}}"
      state: present
    with_items:
      - Raj
      - Vaibhav
      - Sai
