---
- name: This Playbook is to create user using variable
  hosts: all
  become: true
  vars:
    name: Akash
  tasks:
  - name: creating user {{name}}
    user:
      name: "{{name}}"
      state: present
