---
- name: This Playbook is to delete user
  hosts: all
  become: true
  vars:
    name: Akash
  tasks:
  - name: deleting user {{name}}
    user:
      name: "{{name}}"
      state: absent
      remove: yes
