---
- name: This Playbook is to install apache with handler
  hosts: all
  become: true
  tasks:
  - name: intsall httpd pacakge
    yum:
      name: httpd
      state: present
    notify: start httpd service

  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
