---
- name: This Playbook is to install httpd package
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed

  - name: start httpd service
    service:
      name: httpd
      state: started
