---
- name: This Playbook is to install apache package
  hosts: all
  become: true
  tasks:
  - name: install https package
    yum:
     name: httpd
     state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: instal apache2 package
    apt:
     name: apache2
     state: installed
    when: ansible_os_family == "Debian"

  - name: start apache service
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"
